server:
  port: 8080

spring:
  application:
    name: api-gateway

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

  cloud:
    gateway:
      routes:
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/email/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**