spring:
  application:
    name: user-service

  cloud:
    circuitbreaker:
      resilience4j:
        instances:
          departmentService:
            slidingWindowSize: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 10000ms
            permittedNumberOfCallsInHalfOpenState: 2
            minimumNumberOfCalls: 1

  config:
    import: "optional:configserver:http://localhost:8088"

  main:
    allow-bean-definition-overriding: true
